### ISSUE TITLE
Any chance to also support std::array ?

### ISSUE THREAD

**Issue by talgalili** [digEmAll/stdvectors#2]
It might be faster for filling in a vector with values. For example, when running a simulation/permutation/bootstrap - where the number of simulations is known upfront, but using the native R solution `x[i] <- sim_result` forces a re-creation of the vector on a regular basis. A mutable object would be helpful in such a case.

**Comment by digEmAll** [comment]
Actually, R base vectors are smart enough to avoid vector copy when you replace a value, that's the reason why `stdvectorReplace(sdv,i,newval)` has the same performance as `v[i] <- newval` (actually is slightly worse, probably because of the bigger overhead in Rcpp<->R)

That being said, there's not need to include `std::array`, because the performance won't change. In fact usually the difference between `std::vector` and `std::array` is negligible, and it will be swallowed in the overhead.

**Comment by talgalili** [comment]
I've now learned this. Thanks.
http://adv-r.had.co.nz/memory.html#modification
